### ISSUE TITLE
Problems while materializing InNBT card

### ISSUE THREAD

**Issue by Hiranus** [SCLeoX/IntegratedNBT#10]
Please refer to [Bug in Integrated Dynamics](https://github.com/CyclopsMC/IntegratedDynamics/issues/1004) for details. Its 3rd issue in this bug report.
Basically I tried to use InNBT as a workaround for bug in InDy but result is the same - card is not materialized.

**Comment by SCLeoX** [comment]
Thanks for reporting. Is the issue with materializing the NBT extraction cards or the pipe cards? If the issue is with pipe card, it *probably* has nothing to do with Integrated NBT. However, that said, I will watch the issue you linked. If it turns out that there are something need to be fixed in Integrated NBT, I will fix asap.

**Comment by SCLeoX** [comment]
@Hiranus Is this fixed?

**Comment by SCLeoX** [comment]
I assume it is fixed then.
